#!/usr/bin/env python3
from pathlib import Path
import sys

if len(sys.argv) != 2:
    raise SystemExit(f"Usage: {sys.argv[0]} /path/to/3x-ui-source")

root = Path(sys.argv[1]).resolve()
SELF_SIGNED_DIR = "/usr/local/x-ui-singbox/certs/"


def replace_once(rel: str, old: str, new: str, label: str) -> None:
    path = root / rel
    text = path.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"v23 {label}: expected exactly one anchor, found {count}")
    path.write_text(text.replace(old, new, 1), encoding="utf-8")


# Browser/QR export uses the upstream TUIC link builder for both runtime modes.
# A certificate generated by 3Xpatcher is self-signed, so make that fact part of
# the exported client profile instead of requiring users to toggle insecure.
replace_once(
    "frontend/src/lib/xray/inbound-link.ts",
    """  const allowInsecure = externalProxy?.allowInsecure ? '1' : '0';
  url.searchParams.set('allow_insecure', allowInsecure);""",
    f"""  const certificate = String(server.certificate || rawSettings.certificate || '');
  const generatedSelfSigned = certificate.startsWith('{SELF_SIGNED_DIR}');
  const allowInsecure = externalProxy?.allowInsecure || generatedSelfSigned ? '1' : '0';
  url.searchParams.set('allow_insecure', allowInsecure);""",
    "native browser TUIC self-signed export",
)

# Native backend raw subscription. Base params are cloned for external endpoints,
# so setting this before that branch covers both direct and projected links.
replace_once(
    "internal/sub/service.go",
    """\tparams := make(map[string]string)
\tcc := inst.CongestionControl""",
    f"""\tparams := make(map[string]string)
\tif strings.HasPrefix(inst.Certificate, \"{SELF_SIGNED_DIR}\") {{
\t\tparams[\"allow_insecure\"] = \"1\"
\t}}
\tcc := inst.CongestionControl""",
    "native raw TUIC self-signed export",
)

# Native Mihomo export.
replace_once(
    "internal/sub/clash_service.go",
    """\t\t\"udp-relay-mode\":        inst.UDPRelayMode,
\t\t\"reduce-rtt\":            inst.ZeroRTTHandshake,
\t}
\tif len(inst.ALPN) > 0 {""",
    f"""\t\t\"udp-relay-mode\":        inst.UDPRelayMode,
\t\t\"reduce-rtt\":            inst.ZeroRTTHandshake,
\t}}
\tif strings.HasPrefix(inst.Certificate, \"{SELF_SIGNED_DIR}\") {{
\t\tproxy[\"skip-cert-verify\"] = true
\t}}
\tif len(inst.ALPN) > 0 {{""",
    "native Clash TUIC self-signed export",
)

# Supplemental sing-box raw URI export when runtime=singbox but using the same
# native settings.server form.
path = root / "internal/sub/tuic_runtime.go"
text = path.read_text(encoding="utf-8")
old = """\tif alpn := anyStringSlice(server[\"alpn\"]); len(alpn) > 0 {
\t\tparams[\"alpn\"] = strings.Join(alpn, \",\")
\t}
\treturn true
}"""
if old not in text:
    # The current helper may have []any normalization rather than anyStringSlice.
    old = """\tif raw, ok := server[\"alpn\"].([]any); ok {
\t\tvalues := make([]string, 0, len(raw))
\t\tfor _, item := range raw {
\t\t\tif value, ok := item.(string); ok && strings.TrimSpace(value) != \"\" {
\t\t\t\tvalues = append(values, strings.TrimSpace(value))
\t\t\t}
\t\t}
\t\tif len(values) > 0 {
\t\t\tparams[\"alpn\"] = strings.Join(values, \",\")
\t\t}
\t}
\treturn true
}"""
new = old.replace(
    "\treturn true\n}",
    f"\tif cert, _ := server[\"certificate\"].(string); strings.HasPrefix(strings.TrimSpace(cert), \"{SELF_SIGNED_DIR}\") {{\n\t\tparams[\"allow_insecure\"] = \"1\"\n\t}}\n\treturn true\n}}",
)
count = text.count(old)
if count != 1:
    raise SystemExit(f"v23 sing-box raw TUIC self-signed export: expected one anchor, found {count}")
path.write_text(text.replace(old, new, 1), encoding="utf-8")

print("V23 TUIC self-signed client export applied.")
